Home/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.home, name="home_page"),
    url(r'^query/$', views.query, name="query")
]

PrinceProduct/urls.py
from django.urls import path
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.contrib import admin

from PrinceProduct import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('Home.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Home/models.py
from django.db import models
from . import utils

upload_path_images = 'Media/images/'


# upload_path_category = 'Media/Category/'


def category_icon_path(instance, filename):
    extension = filename.split('.')
    extension = extension[len(extension) - 1]
    test = instance.name
    name = ''.join(e for e in test if e.isalnum())
    # print(name)
    return 'Media/Category/{0}/{1}.{2}'.format(name, name, extension)


def product_media_path(instance, filename):
    extension = filename.split('.')
    extension = extension[len(extension) - 1]
    name = instance.name
    name = ''.join(e for e in name if e.isalnum())
    return 'Media/Categories/{0}/{1}/{2}.{3}'.format(''.join(e for e in instance.category.name if e.isalnum()), name,
                                                     name,
                                                     extension.lower())


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=256)
    description = models.TextField()
    position = models.IntegerField()
    thumbnail = models.ImageField(upload_to=category_icon_path)

    class Meta:
        ordering = ['position']

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=256)
    description = models.TextField()
    position = models.IntegerField()
    price = models.IntegerField(blank=True, null=True)
    image = models.ImageField(upload_to=product_media_path, null=True)
    amazon_url = models.CharField(max_length=1000, default="", null=True,blank=True)

    class Meta:
        ordering = ['position']

    def __str__(self):
        return self.category.name + self.name

Home/views.py
from django.core.mail import send_mail
from django.http import HttpResponse
from django.shortcuts import render

from Home.models import Category
import copy


def home(request):
    categories = Category.objects.all().order_by('position')
    product_data = []
    for each_categoty in categories:
        temp = []
        for each_product in each_categoty.product_set.all():
            temp.append({
                'name': each_product.name,
                'description': each_product.description,
                'price': str(each_product.price),
                'amazon_url': str(each_product.amazon_url),
                'image': each_product.image.url
            })
        product_data.append(copy.deepcopy(temp))
    return render(request, "Home/index.html", {'product_data': product_data, 'categories': categories})


def query(request):
    if request.method == 'POST':
        # print(request.POST)
        user_name = request.POST.get('name')
        user_mail = request.POST.get('email')
        user_msg = request.POST.get('message')
        user_ph = request.POST.get('phone')
        to_list = [
            ''
        ]
        send_mail(subject="Mail by " + user_name, message="", from_email=user_mail, recipient_list=to_list,
                  fail_silently=False,
                  html_message=user_msg + "<br>" + user_ph)

        return HttpResponse("Success")

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Prince Products</title>
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet'
          type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
    <link href="{% static 'css/agency.min.css' %}" rel="stylesheet">
    <link rel="shortcut icon" type="image/svg" href="{% static 'img/logo.svg' %}">
    <meta name="theme-color" content="#FDC832">

    {% block style %}
    {% endblock style %}
    <style>
        #page-top {
            overflow-x: hidden !important;
        }
    </style>
</head>

<body id="page-top" class="index">
{% block body %}
{% endblock body %}
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.easing.min.js' %}"></script>
<script src="{% static 'js/jqBootstrapValidation.js' %}"></script>
<script>
     $(function () {


            $("#contactForm input,#contactForm textarea").jqBootstrapValidation({
                preventSubmit: true,

                submitError: function ($form, event, errors) {
                    // additional error messages or events
                },
                submitSuccess: function ($form, event) {
                    event.preventDefault(); // prevent default submit behaviour
                    // get values from FORM
                    var name = $("input#name").val();
                    var email = $("input#email").val();
                    var phone = $("input#phone").val();
                    var message = $("textarea#message").val();
                    var firstName = name; // For Success/Failure Message
                    // Check for white space in name for Success/Fail message
                    if (firstName.indexOf(' ') >= 0) {
                        firstName = name.split(' ').slice(0, -1).join(' ');
                    }
                    $.ajax({
                        url: "{% url 'home:query' %}",
                        type: "POST",
                        data: {
                            'csrfmiddlewaretoken': "{{ csrf_token }}",
                            name: name,
                            phone: phone,
                            email: email,
                            message: message
                        },
                        cache: false,
                        success: function () {
                            // Success message
                            $('#success').html("<div class='alert alert-success'>");
                            $('#success > .alert-success').html("<button type='button' class='close' data-dismiss='alert' aria-hidden='true'>&times;")
                                .append("</button>");
                            $('#success > .alert-success')
                                .append("<strong>Your message has been sent. </strong>");
                            $('#success > .alert-success')
                                .append('</div>');

                            //clear all fields
                            $('#contactForm').trigger("reset");
                        },
                        error: function () {
                            // Fail message
                            $('#success').html("<div class='alert alert-danger'>");
                            $('#success > .alert-danger').html("<button type='button' class='close' data-dismiss='alert' aria-hidden='true'>&times;")
                                .append("</button>");
                            $('#success > .alert-danger').append($("<strong>").text("Sorry " + firstName + ", it seems that my mail server is not responding. Please try again later!"));
                            $('#success > .alert-danger').append('</div>');
                            //clear all fields
                            $('#contactForm').trigger("reset");
                        },
                    });
                },
                filter: function () {
                    return $(this).is(":visible");
                },
            });
            $("a[data-toggle=\"tab\"]").click(function (e) {
                e.preventDefault();
                $(this).tab("show");
            });
        });


        /*When clicking on Full hide fail/success boxes */
        $('#name').focus(function () {
            $('#success').html('');
        });
</script>
<script src="{% static 'js/agency.min.js' %}"></script>
{% block script %}
{% endblock script %}
</body>

</html>